<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Twig_' => array($vendorDir . '/twig/twig/lib'),
    'PEAR' => array($vendorDir . '/pear/pear_exception'),
    'Console' => array($vendorDir . '/pear/console_getopt'),
    'Archive_Tar' => array($vendorDir . '/pear/archive_tar'),
    '' => array($vendorDir . '/pear/pear-core-minimal/src'),
);
