<?php return array(
    'root' => array(
        'pretty_version' => '3.0.2-rc1',
        'version' => '3.0.2.0-RC1',
        'type' => 'project',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(),
        'reference' => 'c5d5379c492059a80eb72cc1dab148dd6e82705f',
        'name' => 'combodo/itop',
        'dev' => true,
    ),
    'versions' => array(
        'combodo/itop' => array(
            'pretty_version' => '3.0.2-rc1',
            'version' => '3.0.2.0-RC1',
            'type' => 'project',
            'install_path' => __DIR__ . '/../../',
            'aliases' => array(),
            'reference' => 'c5d5379c492059a80eb72cc1dab148dd6e82705f',
            'dev_requirement' => false,
        ),
        'combodo/tcpdf' => array(
            'pretty_version' => '6.4.4',
            'version' => '6.4.4.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../combodo/tcpdf',
            'aliases' => array(),
            'reference' => '0e31c013ccd000aa6762e9186778aa6e259ac8e8',
            'dev_requirement' => false,
        ),
        'container-interop/container-interop' => array(
            'pretty_version' => '1.2.0',
            'version' => '1.2.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../container-interop/container-interop',
            'aliases' => array(),
            'reference' => '79cbf1341c22ec75643d841642dd5d6acd83bdb8',
            'dev_requirement' => false,
        ),
        'container-interop/container-interop-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '^1.2',
            ),
        ),
        'doctrine/lexer' => array(
            'pretty_version' => '1.2.3',
            'version' => '1.2.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/lexer',
            'aliases' => array(),
            'reference' => 'c268e882d4dbdd85e36e4ad69e02dc284f89d229',
            'dev_requirement' => false,
        ),
        'egulias/email-validator' => array(
            'pretty_version' => '2.1.25',
            'version' => '2.1.25.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../egulias/email-validator',
            'aliases' => array(),
            'reference' => '0dbf5d78455d4d6a41d186da50adc1122ec066f4',
            'dev_requirement' => false,
        ),
        'firebase/php-jwt' => array(
            'pretty_version' => 'v5.5.1',
            'version' => '5.5.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../firebase/php-jwt',
            'aliases' => array(),
            'reference' => '83b609028194aa042ea33b5af2d41a7427de80e6',
            'dev_requirement' => false,
        ),
        'guzzlehttp/guzzle' => array(
            'pretty_version' => '6.5.8',
            'version' => '6.5.8.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../guzzlehttp/guzzle',
            'aliases' => array(),
            'reference' => 'a52f0440530b54fa079ce76e8c5d196a42cad981',
            'dev_requirement' => false,
        ),
        'guzzlehttp/promises' => array(
            'pretty_version' => '1.5.1',
            'version' => '1.5.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../guzzlehttp/promises',
            'aliases' => array(),
            'reference' => 'fe752aedc9fd8fcca3fe7ad05d419d32998a06da',
            'dev_requirement' => false,
        ),
        'guzzlehttp/psr7' => array(
            'pretty_version' => '1.9.0',
            'version' => '1.9.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../guzzlehttp/psr7',
            'aliases' => array(),
            'reference' => 'e98e3e6d4f86621a9b75f623996e6bbdeb4b9318',
            'dev_requirement' => false,
        ),
        'laminas/laminas-loader' => array(
            'pretty_version' => '2.6.1',
            'version' => '2.6.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../laminas/laminas-loader',
            'aliases' => array(),
            'reference' => '5d01c2c237ae9e68bec262f339947e2ea18979bc',
            'dev_requirement' => false,
        ),
        'laminas/laminas-mail' => array(
            'pretty_version' => '2.12.5',
            'version' => '2.12.5.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../laminas/laminas-mail',
            'aliases' => array(),
            'reference' => 'ed5b36a0deef4ffafe6138c2ae9cafcffafab856',
            'dev_requirement' => false,
        ),
        'laminas/laminas-mime' => array(
            'pretty_version' => '2.7.4',
            'version' => '2.7.4.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../laminas/laminas-mime',
            'aliases' => array(),
            'reference' => 'e45a7d856bf7b4a7b5bd00d6371f9961dc233add',
            'dev_requirement' => false,
        ),
        'laminas/laminas-servicemanager' => array(
            'pretty_version' => '3.5.2',
            'version' => '3.5.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../laminas/laminas-servicemanager',
            'aliases' => array(),
            'reference' => '0669e1eec8d9f61e35a5bc5012796d49f418b259',
            'dev_requirement' => false,
        ),
        'laminas/laminas-stdlib' => array(
            'pretty_version' => '3.2.1',
            'version' => '3.2.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../laminas/laminas-stdlib',
            'aliases' => array(),
            'reference' => '2b18347625a2f06a1a485acfbc870f699dbe51c6',
            'dev_requirement' => false,
        ),
        'laminas/laminas-validator' => array(
            'pretty_version' => '2.13.5',
            'version' => '2.13.5.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../laminas/laminas-validator',
            'aliases' => array(),
            'reference' => 'd334dddda43af263d6a7e5024fd2b013cb6981f7',
            'dev_requirement' => false,
        ),
        'laminas/laminas-zendframework-bridge' => array(
            'pretty_version' => '1.1.1',
            'version' => '1.1.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../laminas/laminas-zendframework-bridge',
            'aliases' => array(),
            'reference' => '6ede70583e101030bcace4dcddd648f760ddf642',
            'dev_requirement' => false,
        ),
        'league/oauth2-client' => array(
            'pretty_version' => '2.6.1',
            'version' => '2.6.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../league/oauth2-client',
            'aliases' => array(),
            'reference' => '2334c249907190c132364f5dae0287ab8666aa19',
            'dev_requirement' => false,
        ),
        'league/oauth2-google' => array(
            'pretty_version' => '3.0.4',
            'version' => '3.0.4.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../league/oauth2-google',
            'aliases' => array(),
            'reference' => '6b79441f244040760bed5fdcd092a2bda7cf34c6',
            'dev_requirement' => false,
        ),
        'nikic/php-parser' => array(
            'pretty_version' => 'v4.13.2',
            'version' => '4.13.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../nikic/php-parser',
            'aliases' => array(),
            'reference' => '210577fe3cf7badcc5814d99455df46564f3c077',
            'dev_requirement' => false,
        ),
        'paragonie/random_compat' => array(
            'pretty_version' => 'v2.0.18',
            'version' => '2.0.18.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../paragonie/random_compat',
            'aliases' => array(),
            'reference' => '0a58ef6e3146256cc3dc7cc393927bcc7d1b72db',
            'dev_requirement' => false,
        ),
        'pear/archive_tar' => array(
            'pretty_version' => '1.4.14',
            'version' => '1.4.14.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../pear/archive_tar',
            'aliases' => array(),
            'reference' => '4d761c5334c790e45ef3245f0864b8955c562caa',
            'dev_requirement' => false,
        ),
        'pear/console_getopt' => array(
            'pretty_version' => 'v1.4.3',
            'version' => '1.4.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../pear/console_getopt',
            'aliases' => array(),
            'reference' => 'a41f8d3e668987609178c7c4a9fe48fecac53fa0',
            'dev_requirement' => false,
        ),
        'pear/pear-core-minimal' => array(
            'pretty_version' => 'v1.10.10',
            'version' => '1.10.10.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../pear/pear-core-minimal',
            'aliases' => array(),
            'reference' => '625a3c429d9b2c1546438679074cac1b089116a7',
            'dev_requirement' => false,
        ),
        'pear/pear_exception' => array(
            'pretty_version' => 'v1.0.2',
            'version' => '1.0.2.0',
            'type' => 'class',
            'install_path' => __DIR__ . '/../pear/pear_exception',
            'aliases' => array(),
            'reference' => 'b14fbe2ddb0b9f94f5b24cf08783d599f776fff0',
            'dev_requirement' => false,
        ),
        'pelago/emogrifier' => array(
            'pretty_version' => 'v3.1.0',
            'version' => '3.1.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../pelago/emogrifier',
            'aliases' => array(),
            'reference' => 'f6a5c7d44612d86c3901c93f1592f5440e6b2cd8',
            'dev_requirement' => false,
        ),
        'psr/cache' => array(
            'pretty_version' => '1.0.1',
            'version' => '1.0.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/cache',
            'aliases' => array(),
            'reference' => 'd11b50ad223250cf17b86e38383413f5a6764bf8',
            'dev_requirement' => false,
        ),
        'psr/cache-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'psr/container' => array(
            'pretty_version' => '1.0.0',
            'version' => '1.0.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/container',
            'aliases' => array(),
            'reference' => 'b7ce3b176482dbbc1245ebf52b181af44c2cf55f',
            'dev_requirement' => false,
        ),
        'psr/container-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '^1.0',
                1 => '1.0',
            ),
        ),
        'psr/http-message' => array(
            'pretty_version' => '1.0.1',
            'version' => '1.0.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/http-message',
            'aliases' => array(),
            'reference' => 'f6561bf28d520154e4b0ec72be95418abe6d9363',
            'dev_requirement' => false,
        ),
        'psr/http-message-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'psr/log' => array(
            'pretty_version' => '1.1.2',
            'version' => '1.1.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/log',
            'aliases' => array(),
            'reference' => '446d54b4cb6bf489fc9d75f55843658e6f25d801',
            'dev_requirement' => false,
        ),
        'psr/log-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'psr/simple-cache' => array(
            'pretty_version' => '1.0.1',
            'version' => '1.0.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/simple-cache',
            'aliases' => array(),
            'reference' => '408d5eafb83c57f6365a3ca330ff23aa4a5fa39b',
            'dev_requirement' => false,
        ),
        'psr/simple-cache-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'ralouphie/getallheaders' => array(
            'pretty_version' => '3.0.3',
            'version' => '3.0.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../ralouphie/getallheaders',
            'aliases' => array(),
            'reference' => '120b605dfeb996808c31b6477290a714d356e822',
            'dev_requirement' => false,
        ),
        'rsky/pear-core-min' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v1.10.10',
            ),
        ),
        'scssphp/scssphp' => array(
            'pretty_version' => 'v1.10.3',
            'version' => '1.10.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../scssphp/scssphp',
            'aliases' => array(),
            'reference' => '0f1e1516ed2412ad43e42a6a319e77624ba1f713',
            'dev_requirement' => false,
        ),
        'swiftmailer/swiftmailer' => array(
            'pretty_version' => 'v6.3.0',
            'version' => '6.3.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../swiftmailer/swiftmailer',
            'aliases' => array(),
            'reference' => '8a5d5072dca8f48460fce2f4131fcc495eec654c',
            'dev_requirement' => false,
        ),
        'symfony/cache' => array(
            'pretty_version' => 'v3.4.47',
            'version' => '3.4.47.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/cache',
            'aliases' => array(),
            'reference' => 'a7a14c4832760bd1fbd31be2859ffedc9b6ff813',
            'dev_requirement' => false,
        ),
        'symfony/class-loader' => array(
            'pretty_version' => 'v3.4.47',
            'version' => '3.4.47.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/class-loader',
            'aliases' => array(),
            'reference' => 'a22265a9f3511c0212bf79f54910ca5a77c0e92c',
            'dev_requirement' => false,
        ),
        'symfony/config' => array(
            'pretty_version' => 'v3.4.47',
            'version' => '3.4.47.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/config',
            'aliases' => array(),
            'reference' => 'bc6b3fd3930d4b53a60b42fe2ed6fc466b75f03f',
            'dev_requirement' => false,
        ),
        'symfony/console' => array(
            'pretty_version' => 'v3.4.47',
            'version' => '3.4.47.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/console',
            'aliases' => array(),
            'reference' => 'a10b1da6fc93080c180bba7219b5ff5b7518fe81',
            'dev_requirement' => false,
        ),
        'symfony/css-selector' => array(
            'pretty_version' => 'v3.4.47',
            'version' => '3.4.47.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/css-selector',
            'aliases' => array(),
            'reference' => 'da3d9da2ce0026771f5fe64cb332158f1bd2bc33',
            'dev_requirement' => false,
        ),
        'symfony/debug' => array(
            'pretty_version' => 'v3.4.47',
            'version' => '3.4.47.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/debug',
            'aliases' => array(),
            'reference' => 'ab42889de57fdfcfcc0759ab102e2fd4ea72dcae',
            'dev_requirement' => false,
        ),
        'symfony/dependency-injection' => array(
            'pretty_version' => 'v3.4.47',
            'version' => '3.4.47.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/dependency-injection',
            'aliases' => array(),
            'reference' => '51d2a2708c6ceadad84393f8581df1dcf9e5e84b',
            'dev_requirement' => false,
        ),
        'symfony/dotenv' => array(
            'pretty_version' => 'v3.4.47',
            'version' => '3.4.47.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/dotenv',
            'aliases' => array(),
            'reference' => '1022723ac4f56b001d99691d96c6025dbf1404f1',
            'dev_requirement' => false,
        ),
        'symfony/event-dispatcher' => array(
            'pretty_version' => 'v3.4.47',
            'version' => '3.4.47.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/event-dispatcher',
            'aliases' => array(),
            'reference' => '31fde73757b6bad247c54597beef974919ec6860',
            'dev_requirement' => false,
        ),
        'symfony/filesystem' => array(
            'pretty_version' => 'v3.4.47',
            'version' => '3.4.47.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/filesystem',
            'aliases' => array(),
            'reference' => 'e58d7841cddfed6e846829040dca2cca0ebbbbb3',
            'dev_requirement' => false,
        ),
        'symfony/finder' => array(
            'pretty_version' => 'v3.4.47',
            'version' => '3.4.47.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/finder',
            'aliases' => array(),
            'reference' => 'b6b6ad3db3edb1b4b1c1896b1975fb684994de6e',
            'dev_requirement' => false,
        ),
        'symfony/framework-bundle' => array(
            'pretty_version' => 'v3.4.47',
            'version' => '3.4.47.0',
            'type' => 'symfony-bundle',
            'install_path' => __DIR__ . '/../symfony/framework-bundle',
            'aliases' => array(),
            'reference' => '6c95e747b75ddd2af61152ce93bf87299d15710e',
            'dev_requirement' => false,
        ),
        'symfony/http-foundation' => array(
            'pretty_version' => 'v3.4.47',
            'version' => '3.4.47.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/http-foundation',
            'aliases' => array(),
            'reference' => 'b9885fcce6fe494201da4f70a9309770e9d13dc8',
            'dev_requirement' => false,
        ),
        'symfony/http-kernel' => array(
            'pretty_version' => 'v3.4.49',
            'version' => '3.4.49.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/http-kernel',
            'aliases' => array(),
            'reference' => '5aa72405f5bd5583c36ed6e756acb17d3f98ac40',
            'dev_requirement' => false,
        ),
        'symfony/polyfill-apcu' => array(
            'pretty_version' => 'v1.19.0',
            'version' => '1.19.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-apcu',
            'aliases' => array(),
            'reference' => 'b44b51e7814c23bfbd793a16ead5d7ce43ed23c5',
            'dev_requirement' => false,
        ),
        'symfony/polyfill-ctype' => array(
            'pretty_version' => 'v1.19.0',
            'version' => '1.19.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-ctype',
            'aliases' => array(),
            'reference' => 'aed596913b70fae57be53d86faa2e9ef85a2297b',
            'dev_requirement' => false,
        ),
        'symfony/polyfill-iconv' => array(
            'pretty_version' => 'v1.25.0',
            'version' => '1.25.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-iconv',
            'aliases' => array(),
            'reference' => 'f1aed619e28cb077fc83fac8c4c0383578356e40',
            'dev_requirement' => false,
        ),
        'symfony/polyfill-intl-idn' => array(
            'pretty_version' => 'v1.25.0',
            'version' => '1.25.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-intl-idn',
            'aliases' => array(),
            'reference' => '749045c69efb97c70d25d7463abba812e91f3a44',
            'dev_requirement' => false,
        ),
        'symfony/polyfill-intl-normalizer' => array(
            'pretty_version' => 'v1.25.0',
            'version' => '1.25.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-intl-normalizer',
            'aliases' => array(),
            'reference' => '8590a5f561694770bdcd3f9b5c69dde6945028e8',
            'dev_requirement' => false,
        ),
        'symfony/polyfill-mbstring' => array(
            'pretty_version' => 'v1.19.0',
            'version' => '1.19.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-mbstring',
            'aliases' => array(),
            'reference' => 'b5f7b932ee6fa802fc792eabd77c4c88084517ce',
            'dev_requirement' => false,
        ),
        'symfony/polyfill-php56' => array(
            'pretty_version' => 'v1.19.0',
            'version' => '1.19.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-php56',
            'aliases' => array(),
            'reference' => 'ea19621731cbd973a6702cfedef3419768bf3372',
            'dev_requirement' => false,
        ),
        'symfony/polyfill-php70' => array(
            'pretty_version' => 'v1.19.0',
            'version' => '1.19.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-php70',
            'aliases' => array(),
            'reference' => '3fe414077251a81a1b15b1c709faf5c2fbae3d4e',
            'dev_requirement' => false,
        ),
        'symfony/polyfill-php72' => array(
            'pretty_version' => 'v1.25.0',
            'version' => '1.25.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-php72',
            'aliases' => array(),
            'reference' => '9a142215a36a3888e30d0a9eeea9766764e96976',
            'dev_requirement' => false,
        ),
        'symfony/polyfill-util' => array(
            'pretty_version' => 'v1.19.0',
            'version' => '1.19.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-util',
            'aliases' => array(),
            'reference' => '8df0c3e6a4b85df9a5c6f3f2f46fba5c5c47058a',
            'dev_requirement' => false,
        ),
        'symfony/routing' => array(
            'pretty_version' => 'v3.4.47',
            'version' => '3.4.47.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/routing',
            'aliases' => array(),
            'reference' => '3e522ac69cadffd8131cc2b22157fa7662331a6c',
            'dev_requirement' => false,
        ),
        'symfony/stopwatch' => array(
            'pretty_version' => 'v3.4.47',
            'version' => '3.4.47.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/stopwatch',
            'aliases' => array(),
            'reference' => '298b81faad4ce60e94466226b2abbb8c9bca7462',
            'dev_requirement' => true,
        ),
        'symfony/twig-bridge' => array(
            'pretty_version' => 'v3.4.47',
            'version' => '3.4.47.0',
            'type' => 'symfony-bridge',
            'install_path' => __DIR__ . '/../symfony/twig-bridge',
            'aliases' => array(),
            'reference' => '090d19d6f1ea5b9e1d79f372785aa5e5c9cd4042',
            'dev_requirement' => false,
        ),
        'symfony/twig-bundle' => array(
            'pretty_version' => 'v3.4.47',
            'version' => '3.4.47.0',
            'type' => 'symfony-bundle',
            'install_path' => __DIR__ . '/../symfony/twig-bundle',
            'aliases' => array(),
            'reference' => '977b3096e2df96bc8a8d2329e83466cfc30c373d',
            'dev_requirement' => false,
        ),
        'symfony/var-dumper' => array(
            'pretty_version' => 'v3.4.47',
            'version' => '3.4.47.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/var-dumper',
            'aliases' => array(),
            'reference' => '0719f6cf4633a38b2c1585140998579ce23b4b7d',
            'dev_requirement' => true,
        ),
        'symfony/web-profiler-bundle' => array(
            'pretty_version' => 'v3.4.47',
            'version' => '3.4.47.0',
            'type' => 'symfony-bundle',
            'install_path' => __DIR__ . '/../symfony/web-profiler-bundle',
            'aliases' => array(),
            'reference' => 'ccb83b3a508f4a683e44f571f127beebdc315ff9',
            'dev_requirement' => true,
        ),
        'symfony/yaml' => array(
            'pretty_version' => 'v3.4.47',
            'version' => '3.4.47.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/yaml',
            'aliases' => array(),
            'reference' => '88289caa3c166321883f67fe5130188ebbb47094',
            'dev_requirement' => false,
        ),
        'tecnickcom/tcpdf' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '6.4.4',
            ),
        ),
        'thenetworg/oauth2-azure' => array(
            'pretty_version' => 'v2.1.1',
            'version' => '2.1.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../thenetworg/oauth2-azure',
            'aliases' => array(),
            'reference' => '06fb2d620fb6e6c934f632c7ec7c5ea2e978a844',
            'dev_requirement' => false,
        ),
        'true/punycode' => array(
            'pretty_version' => 'v2.1.1',
            'version' => '2.1.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../true/punycode',
            'aliases' => array(),
            'reference' => 'a4d0c11a36dd7f4e7cd7096076cab6d3378a071e',
            'dev_requirement' => false,
        ),
        'twig/twig' => array(
            'pretty_version' => 'v1.43.1',
            'version' => '1.43.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../twig/twig',
            'aliases' => array(),
            'reference' => '2311602f6a208715252febe682fa7c38e56a3373',
            'dev_requirement' => false,
        ),
        'zendframework/zend-loader' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '2.6.1',
            ),
        ),
        'zendframework/zend-mail' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '^2.10.0',
            ),
        ),
        'zendframework/zend-mime' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '^2.7.2',
            ),
        ),
        'zendframework/zend-servicemanager' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '^3.4.0',
            ),
        ),
        'zendframework/zend-stdlib' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '3.2.1',
            ),
        ),
        'zendframework/zend-validator' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '^2.13.0',
            ),
        ),
    ),
);
