<?php
//
// iTop module definition file
//

SetupWebPage::AddModule(
	__FILE__, // Path to the current file, all other file names are relative to the directory containing this file
	'itop-bridge-cmdb-ticket/3.0.0',
	array(
		// Identification
		//
		'label' => 'Bridge for CMDB and Ticket',
		'category' => 'business',

		// Setup
		//
		'dependencies' => array(
				'itop-config-mgmt/2.7.1',
				'itop-tickets/2.7.0',
				'itop-service-mgmt/2.7.1 || itop-service-mgmt-provider/2.7.1',
		),
		'mandatory' => false,
		'visible' => false,
		'auto_select' => 'SetupInfo::ModuleIsSelected("itop-config-mgmt") && SetupInfo::ModuleIsSelected("itop-tickets") && (SetupInfo::ModuleIsSelected("itop-service-mgmt") || SetupInfo::ModuleIsSelected("itop-service-mgmt-provider")) ',

		// Components
		//
		'datamodel' => array(
			'model.itop-bridge-cmdb-ticket.php', // Contains the PHP code generated by the "compilation" of datamodel.itop-cmdb-ticket-bridge.xml
		),
		'webservice' => array(
			
		),
		'data.struct' => array(
			// add your 'structure' definition XML files here,
		),
		'data.sample' => array(
			// add your sample data XML files here,
		),
		
		// Documentation
		//
		'doc.manual_setup' => '', // hyperlink to manual setup documentation, if any
		'doc.more_information' => '', // hyperlink to more information, if any 

		// Default settings
		//
		'settings' => array(
			// Module specific settings go here, if any
		),
	)
);


?>
