<?php

//
// phpMyORM configuration file
//
// To be manually edited (or generated by the configuration wizard)
//
// The file is used in MetaModel::LoadConfig() which does all the necessary initialization job
//

$MySettings = array(
	'db_host' => 'localhost',
	'db_user' => 'RomainDBLogin',
	'db_pwd' => '',
	'db_name' => 'TestFarm',
	'db_subname' => '', // use it to differentiate two applications instances running on the same DB
);

// Modules: file names should be specified as a absolute paths

$MyModules = array(
	'application' => array (
		// to be continued...
	),
	'business' => array (
		'../business/test_farm.class.inc.php',
		// to be continued...
	),
	'addons' => array (
		//'user rights' => '/addons/userrights/userrightsnull.class.inc.php', // or userrightsmatrix.class.inc.php
		// other modules to come later
	)
);

?>
