<?php

//
// phpMyORM configuration file
//
// To be manually edited (or generated by the configuration wizard)
//
// The file is used in MetaModel::LoadConfig() which does all the necessary initialization job
//

$MySettings = array(
	'db_host' => 'localhost',
	'db_user' => 'itop',
	'db_pwd' => '1T0p',
	'db_name' => 'itopv06',
	'db_subname' => '', // use it to differentiate two applications instances running on the same DB
);

// Modules: file names should be specified as a absolute paths

$MyModules = array(
	'application' => array (
		'../application/menunode.class.inc.php',
		'../application/audit.rule.class.inc.php',
		// to be continued...
	),
	'business' => array (
		// to be continued...
	),
	'addons' => array (
		'user rights' => '../addons/userrights/userrightsprofile.class.inc.php', 
		// other modules to come later
	)
);


?>
