<?php
/**
 * Copyright (C) 2013-2024 Combodo SAS
 * This file is part of iTop.
 * iTop is free software; you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * iTop is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 * You should have received a copy of the GNU Affero General Public License
 */

namespace Combodo\iTop\Test\UnitTest\Integration;

use ApplicationException;
use Combodo\iTop\Test\UnitTest\ItopTestCase;
use Combodo\iTop\Test\UnitTest\XmlModule;
use Combodo\iTop\Test\UnitTest\XmlModuleMetaInfo;
use utils;

require_once __DIR__ . '/XmlModuleMetaInfo.php';
require_once __DIR__ . '/XmlModule.php';
require_once __DIR__ . '/iTopModulesDependencyValidationService.php';

use ModuleInstallerAPI;
/**
 * @package Combodo\iTop\Test\UnitTest\Setup
 */
class iTopModulesDependencyTest extends ItopTestCase {
	private iTopModulesDependencyValidationService $oiTopModulesDependencyValidationService;

	private array $aFilesToRemove = [];

	protected function setUp(): void
	{
		parent::setUp(); // TODO: Change the autogenerated stub
	}

	protected function tearDown(): void
	{
		parent::tearDown(); // TODO: Change the autogenerated stub
		foreach ($this->aFilesToRemove as $sTmpFile){
			@unlink($sTmpFile);
		}
		iTopModulesDependencyValidationService::SetInstance(null);
	}

	/**
	 * Module dependency validation: make sure dependencies are correct toward classes/interfaces coming from PHP/Xml datamodel files
	 */
	public function testReadModuleFileData()
	{
		iTopModulesDependencyValidationService::GetInstance()->FetchAllDependenciesViaModulesFiles();
		$this->testModulesBasedOnDMFilesOnly();
	}

	/**
	 * Module dependency validation: make sure dependencies are correct toward classes/interfaces coming from Xml datamodel files
	 */
	public function testModulesBasedOnDMFilesOnly()
	{
		iTopModulesDependencyValidationService::GetInstance()->FetchAllDependenciesViaDM();

		$aErrors=[];
		/** @var XmlModule $oXmlModule */
		foreach (iTopModulesDependencyValidationService::GetInstance()->aModules as $sModuleName => $oXmlModule) {
			$aCurrentDeps = iTopModulesDependencyValidationService::GetInstance()::$aModulesDataByModuleName[$sModuleName][2]['dependencies'] ?? [];
			$aModuleErrors=[];
			foreach ($oXmlModule->aDependencyModulesNames as $sDepModuleName => $oXmlModule2){
				$sXmlUIDs = implode('|', $oXmlModule->aXMlMetaInfosByModuleNames[$sDepModuleName]);
				$bResolved=false;
				foreach ($aCurrentDeps as $sDepString){
					$oModuleDependency = new \iTopCoreModuleDependency($sDepString);

					if (in_array($sDepModuleName, $oModuleDependency->GetPotentialPrerequisiteModuleNames())) {
						$bResolved=true;
						break;
					}

					foreach ($oModuleDependency->GetPotentialPrerequisiteModuleNames() as $sPotentialDepModuleName){
						/** @var XmlModule $oXmlModule2 */
						$oXmlModule2 = iTopModulesDependencyValidationService::GetInstance()->aModules[$sPotentialDepModuleName]??null;

						if (! is_null($oXmlModule2) && $oXmlModule2->Depends($sDepModuleName)){
							$bResolved=true;
							break;
						}
					}

					if ($bResolved) {
						break;
					}
				}

				if (! $bResolved){
					$aModuleErrors []= "$sModuleName depends on $sDepModuleName but missing in module dependencies: " . implode(' & ', $aCurrentDeps) . ". ($sXmlUIDs)";
				}
			}

			if (count($aModuleErrors)){
				$aErrors[$sModuleName]=$aModuleErrors;
			}
		}

		$this->assertEquals(0, count($aErrors), var_export($aErrors, true));

	}

	public function testListDeclaredFullnameClassesFromPhpFile()
	{
		$aExpected = [
			'CMDBChangeOp',
			'CMDBChangeOpCreate',
			'CMDBChangeOpDelete',
			'CMDBChangeOpSetAttribute',
			'CMDBChangeOpSetAttributeScalar',
			'CMDBChangeOpSetAttributeTagSet',
			'CMDBChangeOpSetAttributeURL',
			'CMDBChangeOpSetAttributeBlob',
			'CMDBChangeOpSetAttributeOneWayPassword',
			'CMDBChangeOpSetAttributeEncrypted',
			'CMDBChangeOpSetAttributeText',
			'CMDBChangeOpSetAttributeLongText',
			'CMDBChangeOpSetAttributeHTML',
			'CMDBChangeOpSetAttributeCaseLog',
			'CMDBChangeOpPlugin',
			'CMDBChangeOpSetAttributeLinksAddRemove',
			'CMDBChangeOpSetAttributeLinksTune',
			'CMDBChangeOpSetAttributeCustomFields',
			'iCMDBChangeOp',
		];
		$this->assertEquals($aExpected, iTopModulesDependencyValidationService::GetInstance()->ListDeclaredFullnameClassesFromPhpFile(APPROOT . 'core/cmdbchangeop.class.inc.php'));
	}

	public function testListDeclaredFullnameClassesFromAutoloadFile()
	{
		$aExpected = [
			'Combodo\iTop\OAuthClient\Controller\AjaxOauthClientController',
			'Combodo\iTop\OAuthClient\Controller\OAuthClientController',
			'Combodo\iTop\OAuthClient\Service\ApplicationUIExtension',
			'Combodo\iTop\OAuthClient\Service\PopupMenuExtension',
		];
		$this->assertEquals($aExpected, iTopModulesDependencyValidationService::GetInstance()->ListDeclaredFullnameClassesFromPhpFile(APPROOT . 'datamodels/2.x/itop-oauth-client/vendor/autoload.php'));
	}

	public function testReadModuleMetaInfo()
	{
		$this->markTestSkipped();
		$aExpected = [
			'/var/www/html/iTop/datamodels/2.x/itop-portal-base/module.itop-portal-base.php',
			'itop-portal-base/3.2.1',
			[
				'label' => 'Portal Development Library',
		        'category' => 'Portal',
		        'dependencies' => [ 'itop-attachments/3.2.1' ],
		        'mandatory' => true,
		        'visible' => false,
		        'datamodel' => [ 'portal/vendor/autoload.php' ],
		        'webservice' => [],
		        'dictionary' => [],
		        'data.struct' => [],
		        'data.sample' => [],
		        'doc.manual_setup' => '',
		        'doc.more_information' => '',
		        'settings' => [],
			],
		];
		$this->assertEquals($aExpected, iTopModulesDependencyValidationService::GetInstance()->GetModuleMetainfo('itop-portal-base'));
	}

	public function testGetFirstFoundDepsUID() {
		$sOutput=<<<TXT
/var/www/html/Professional-3.2.1-16428/web/datamodels/2.x/authent-token/src/Hook/MyAccountSectionTabContentExtension.php:Combodo\iTop\MyAccount\Hook\iMyAccountTabContentExtension
TXT;

		$this->assertEquals('Combodo\iTop\MyAccount\Hook\iMyAccountTabContentExtension', iTopModulesDependencyValidationService::GetInstance()->GetFirstFoundDepsUID($sOutput));


		$sOutput=<<<TXT
/var/www/html/Professional-3.2.1-16428/web/datamodels/2.x/authent-token/src/Hook/MyAccountSectionTabContentExtension.php:Combodo\iTop\MyAccount\Hook\iMyAccountTabContentExtension
/var/www/html/Professional-3.2.1-16428/web/datamodels/2.x/authent-token/src/Hook/MyAccountSectionTabContentExtension2.php:Combodo\iTop\MyAccount\Hook\iMyAccountTabContentExtension2
/var/www/html/Professional-3.2.1-16428/web/datamodels/2.x/authent-token/src/Hook/MyAccountSectionTabContentExtension3.php:Combodo\iTop\MyAccount\Hook\iMyAccountTabContentExtension3
TXT;

		$this->assertEquals('Combodo\iTop\MyAccount\Hook\iMyAccountTabContentExtension', iTopModulesDependencyValidationService::GetInstance()->GetFirstFoundDepsUID($sOutput));
	}
}


