<?php

//
// phpMyORM configuration file
//
// To be manually edited (or generated by the configuration wizard)
//
// The file is used in MetaModel::LoadConfig() which does all the necessary initialization job
//


$MySettings = array(
	'db_host' => 'localhost',
	'db_user' => 'itop',
	'db_pwd' => '1T0p',
	'db_name' => 'TestBizModelGenericItop',
	'db_subname' => 'tribute2itop', // use it to differentiate two applications instances running on the same DB
);

// Modules: file names should be specified as a absolute paths

$MyModules = array(
	'application' => array (
		// to be continued...
	),
	'business' => array (
		'../business/business_test.class.inc.php'
		// to be continued...
	),
	'addons' => array (
		// other modules to come later
	)
);


?>
