<?php
/**
 * @copyright   Copyright (C) 2010-2022 Combodo SARL
 * @license     http://opensource.org/licenses/AGPL-3.0
 */

namespace Combodo\iTop\OAuthClient\Service;

use AbstractApplicationObjectExtension;
use Exception;
use OAuthClient;

class ApplicationObjectExtension extends AbstractApplicationObjectExtension
{

	public function OnDBInsert($oObject, $oChange = null)
	{
		if ($oObject instanceof OAuthClient) {
			try {
				// Ask for tokens the first time

				//$response = utils::DoPostRequest($sRestUrl, $aPostedData);
			} catch (Exception $e) {
			}

		}
		parent::OnDBInsert($oObject, $oChange); // TODO: Change the autogenerated stub
	}

}