<?php
//
// iTop module definition file
//

SetupWebPage::AddModule(
	__FILE__, // Path to the current file, all other file names are relative to the directory containing this file
	'itop-container-mgmt/3.2.0',
	array(
		// Identification
		//
		'label' => 'Container management',
		'category' => 'business',

		// Setup
		//
		'dependencies' => array(
			'itop-virtualization-mgmt/3.2.0'
		),
		'mandatory' => false,
		'visible' => true,
		'installer' => 'ContainerTypeInstaller',

		// Components
		//
		'datamodel' => array(
			'model.itop-container-mgmt.php', // Contains the PHP code generated by the "compilation" of datamodel.combodo-container-mgmt.xml
		),
		'webservice' => array(
			
		),
		'data.struct' => array(
			// add your 'structure' definition XML files here,
		),
		'data.sample' => array(
			// add your sample data XML files here,
		),
		
		// Documentation
		//
		'doc.manual_setup' => '', // hyperlink to manual setup documentation, if any
		'doc.more_information' => '', // hyperlink to more information, if any 

		// Default settings
		//
		'settings' => array(
			// Module specific settings go here, if any
		),
	)
);

if (!class_exists('ContainerTypeInstaller'))
{
	// Module installation handler
	//
	class ContainerTypeInstaller extends ModuleInstallerAPI
	{
		/**
		 * Handler called after the creation/update of the database schema
		 *
		 * @param $oConfiguration Config The new configuration of the application
		 * @param $sPreviousVersion string Previous version number of the module (empty string in case of first install)
		 * @param $sCurrentVersion string Current version number of the module
		 *
		 * @throws \Exception
		 */
		public static function AfterDatabaseCreation(Config $oConfiguration, $sPreviousVersion, $sCurrentVersion)
		{
			if ($sPreviousVersion == '') { // First installation
				$oDataLoader = new XMLDataLoader();
				CMDBObject::SetTrackInfo("Initialization ContainerTypeInstaller");
				$oMyChange = CMDBObject::GetCurrentChange();
				$sFileName = dirname(__FILE__)."/data/en_us.data.itop-container-type.xml";
				SetupLog::Info("Uploading Typology values for Containers from file: $sFileName");
				$oDataLoader->StartSession($oMyChange);
				$oDataLoader->LoadFile($sFileName, false, true);
				$oDataLoader->EndSession();
			}
		}
	}
}

?>
