<?php

require_once(APPROOT.'setup/wizardsteps/WizardState.php');
require_once(APPROOT.'setup/wizardsteps/WizardStep.php');
require_once(APPROOT.'setup/wizardsteps/AbstractWizStepInstall.php');
require_once(APPROOT.'setup/wizardsteps/WizStepWelcome.php');
require_once(APPROOT.'setup/wizardsteps/WizStepInstallOrUpgrade.php');
require_once(APPROOT.'setup/wizardsteps/WizStepDetectedInfo.php');
require_once(APPROOT.'setup/wizardsteps/WizStepLicense.php');
require_once(APPROOT.'setup/wizardsteps/WizStepLicense2.php');
require_once(APPROOT.'setup/wizardsteps/AbstractWizStepMiscParams.php');
require_once(APPROOT.'setup/wizardsteps/WizStepAdminAccount.php');
require_once(APPROOT.'setup/wizardsteps/WizStepInstall.php');
require_once(APPROOT.'setup/wizardsteps/WizStepDataAudit.php');
require_once(APPROOT.'setup/wizardsteps/WizStepDBParams.php');
require_once(APPROOT.'setup/wizardsteps/WizStepDone.php');
require_once(APPROOT.'setup/wizardsteps/WizStepInstallMiscParams.php');
require_once(APPROOT.'setup/wizardsteps/WizStepModulesChoice.php');
require_once(APPROOT.'setup/wizardsteps/WizStepSummary.php');
require_once(APPROOT.'setup/wizardsteps/WizStepUpgradeMiscParams.php');
require_once(APPROOT.'setup/wizardsteps/WizStepLandingBeforeAudit.php');
require_once(APPROOT.'setup/wizardcontroller.class.inc.php');
