<?php
/**
 * @copyright   Copyright (C) 2010-__YEAR__ Combodo SARL
 * @license     http://opensource.org/licenses/AGPL-3.0
 */

//
// iTop module definition file
//

SetupWebPage::AddModule(
	__FILE__, // Path to the current file, all other file names are relative to the directory containing this file
	'__module_full_name__',
	[
		// Identification
		//
		'label' => '__module_label__',
		'category' => '__module_category__',

		// Setup
		//
		'dependencies' => [
			__module_dependencies__
		],
		'mandatory' => __module_mandatory__,
		'visible' => __module_visible__,
		__module_setup_handler_class__

		// Components
		//
		'datamodel' => [
			'vendor/autoload.php',
			__module_data_model__, // Contains the PHP code generated by the "compilation" of datamodel.__module_name__.xml
		],
		'webservice' => [],
		'data.struct' => [
			// add your 'structure' definition XML files here,
		],
		'data.sample' => [
			// add your sample data XML files here,
		],

		// Documentation
		//
		'doc.manual_setup' => '', // hyperlink to manual setup documentation, if any
		'doc.more_information' => '', // hyperlink to more information, if any

		// Default settings
		//
		'settings' => [
			// Module specific settings go here, if any
		],
	]
);

__module_setup_handler__
